name: Deploy Telegram Bot to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DOCKER_SSH_KEY }}

      - name: Add remote server to known_hosts
        run: ssh-keyscan -H ${{ secrets.DOCKER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh ${{ secrets.DOCKER_USER }}@${{ secrets.DOCKER_HOST }} '
            cd ~/suai-deadline-bot || git clone https://github.com/${{ github.repository }}.git ~/suai-deadline-bot
            
            cd ~/suai-deadline-bot
            git pull
            
            echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
            
            docker build -t suai-deadline-bot .
            
            docker stop suai-bot-container || true
            docker rm suai-bot-container || true
            
            docker run -d --name suai-bot-container -v $(pwd)/src/database:/app/src/database --restart always suai-deadline-bot
          '